@echo off
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
cd /d "c:\Users\techn\Documents\bof_template\certify"
if not exist bin mkdir bin
echo Compiling cert_cas...
cl.exe /c /GS- /Gs999999999 /Od /Ob1 /Oi- /I. /I../ /D WIN64 cert_cas.c /Fobin/cert_cas.x64.o
echo Compiling cert_find...
cl.exe /c /GS- /Gs999999999 /Od /Ob1 /Oi- /I. /I../ /D WIN64 cert_find.c /Fobin/cert_find.x64.o
echo Compiling cert_request...
cl.exe /c /GS- /Gs999999999 /Od /Ob1 /Oi- /I. /I../ /D WIN64 cert_request.c /Fobin/cert_request.x64.o
echo Compiling cert_download...
cl.exe /c /GS- /Gs999999999 /Od /Ob1 /Oi- /I. /I../ /D WIN64 cert_download.c /Fobin/cert_download.x64.o
echo Compiling cert_forge...
cl.exe /c /GS- /Gs999999999 /Od /Ob1 /Oi- /I. /I../ /D WIN64 cert_forge.c /Fobin/cert_forge.x64.o
echo Compiling cert_manageca...
cl.exe /c /GS- /Gs999999999 /Od /Ob1 /Oi- /I. /I../ /D WIN64 cert_manageca.c /Fobin/cert_manageca.x64.o
echo Compiling cert_request_agent...
cl.exe /c /GS- /Gs999999999 /Od /Ob1 /Oi- /I. /I../ /D WIN64 cert_request_agent.c /Fobin/cert_request_agent.x64.o
echo Compiling cert_pkiobjects...
cl.exe /c /GS- /Gs999999999 /Od /Ob1 /Oi- /I. /I../ /D WIN64 cert_pkiobjects.c /Fobin/cert_pkiobjects.x64.o
echo Done!
